[package]
name = "uq"
version = "0.1.1"
authors = ["Tamir Bahar"]
homepage = "https://github.com/lostutils/uq"
license = "MIT"
description = "sort | uniq alternative."
readme = "README.md"

[dependencies]
clap = "2.29.2" 

[[bin]]
name = "uq"
path = "src/main.rs"